### ISSUE TITLE
Direct download document (QA log template, conversation tool) links broken? (point to github-pages-test)

### ISSUE THREAD

**Issue by pinderc** [ukhsa-collaboration/statistics-production-hub#6]
## What type of issue is this?

- Suggesting a change to a published page

## Details

Very helpful resource, thanks, but looks like some document links are to a now-inaccessible test repo at github-pages-test rather than to assets in this repo e.g.: 
- https://github.com/ukhsa-collaboration/statistics-production-hub/blob/b7d45cfaa1393f99b99ad2eb1406ef9c5a806f45/docs/quality-assurance.md?plain=1#L12
- https://github.com/ukhsa-collaboration/statistics-production-hub/blob/b7d45cfaa1393f99b99ad2eb1406ef9c5a806f45/docs/quality-assurance.md?plain=1#L215

**Comment by BenCuff** [comment]
Thanks @pinderc. It seems some commits crossed wires somehow and this page reverted back to an earlier version. We'll look into how that happened. I've fixed it now anyway so the links should work again.
